version: "3.8"
services:
  db:
    image: mysql/mysql-server:8.0.4
    environment:
      - MYSQL_ROOT_PASSWORD=room11
      - MYSQL_USER=room11
      - MYSQL_PASSWORD=room11
    ports:
      - "33060:3306"
    build:
      context: containers/chatscraper_mysql
      dockerfile: Dockerfile
    #volumes:
    #  - ./containers/chatscraper_mysql/db:/var/lib/mysql